# for production

# building phase
FROM node:alpine as builder
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
# /app/build - its where build will be saved
RUN npm run build

# nginx server phase
FROM nginx

# for exposing port in aws
# EXPOSE 80

COPY --from=builder /app/build /usr/share/nginx/html
# nginx is started by image automatically